---
- name: Add Microsoft repo and key
  shell: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg &&
          mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg &&
          sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
  become: yes

- name: Update repositories cache
  apt:
    update_cache: yes
  become: yes

- name: Install VS Code
  apt:
    name: code
    state: latest
  become: yes

# Alternate installation. Download .deb file and install with that
# The repo and key are automatically installed this way, but the thing is...
# the above method will always get the latest version, whereas this one will get the one
# retrieved on 31.10.2017
#- name: Install Visual Studio Code
#  apt:
#    deb: https://az764295.vo.msecnd.net/stable/b813d12980308015bcd2b3a2f6efa5c810c33ba5/code_1.17.2-1508162334_amd64.deb