---
- name: Update repositories cache
  apt:
    update_cache: yes
  become: yes

- name:  Install gui # and update repositories cache
  apt:
#    update_cache: yes
    name: xubuntu-desktop #could be ubuntu-/lubuntu-/whatever you prefer :)
    state: latest
  become: yes

- name: Install git
  apt:
    name: git
    state: latest
    become: yes