---
- name: Update repositories cache
  apt:
    update_cache: yes
  become: yes

- name:  Install gui # and update repositories cache
  apt:
#    update_cache: yes
    name: xubuntu-desktop #could be ubuntu-/lubuntu-/whatever you prefer :)
    state: latest
  become: yes

- name: Create a "handy" folder for code on the Desktop, because this whole thing is temporary and it just needs to be there for easy access
  file:
    path: /Desktop/code
    state: directory
  become: yes

- name: Install git
  apt:
    name: git
    state: latest
  become: yes

